name: Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Prettier Check
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: prettier
      - name: ESLint Check
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: eslint
